name: ublue main 39
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '30 22 * * 4'  # At 22:30 on Thursday.
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 39
